# Site settings
title:
email:
description: > # this means to ignore newlines until "baseurl:"
  ZBL Services, Inc. is a privately held IT consulting firm specializing in legacy application
  workload modernization and enterprise architecture transformation.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

# User setting
owner: ZBL Services, Inc.
email: tfanelli@zblservices.com
facebook_username: zblservices
twitter_username: timfanelli
github_username: doctorbatch
address:
  - line: P.O. Box 815, Concord, NH 03301
  - line:
  # Feel free to add more lines here
telephone: (603) 268-5150
copyright: 2015 ZBL Services, Inc.

# API settings
google_api_key:

# Build settings
markdown: kramdown
